# sudo: required
language: generic
os: linux
services:
    - docker

before_install:
    - docker build -t winadiw/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true winadiw/docker-react npm run test -- --coverage